### ISSUE TITLE
System.Configuration.ConfigurationErrorsException occurred in NServiceBus.Core.dll

### ISSUE THREAD

**Issue by agiudici** [Particular/NServiceBus.Azure.Samples#16]
Hi,

I'd just downloaded the DynamicHost sample, and opened it in VS2013. It asked me to update the VideoStore project to use the Azure Tools v2.4, and I upgraded it.

I followed the instructions (compile and run the upload script) to zip and upload the projects to storage using the emulator, and that worked fine.

When I hit F5 and run the VideoStore project, a get "System.Configuration.ConfigurationErrorsException occurred in NServiceBus.Core.dll" in the line that says nsb.Start() from the class VideoStote.Host.WorkerRole, saying: 

Faults forwarding requires an error queue to be specified. Please add a 'MessageForwardingInCaseOfFaultConfig' section to your app.config

If I understand correctly, that config section does not have to be setup in the VideoStore.Host project. I think that the VideoStore.Host is trying to behave like a regular NServiceBus endpoint and is not running AsA_Host.

Could be that the update to Azure Tools v2.4 is causing this behaviour? Or am i doing anything wrong?

I'd really appreciate any help with this.

**Comment by yvesgoeleven** [comment]
NserviceBus.Azure is decoupled from the azure tools version, so that should not matter at all. It is indeed strange that it checks for that config setting. That probably means it started the generichost instead of the dynamichost as you suggest indeed. 

Which branch did you run? I'll try to reproduce it (I'm on Azure Tools 2.5 already, so not sure if I can truly repro your scenario, but it probably hasn't anything to do with the tools version imo)

**Comment by yvesgoeleven** [comment]
There were bad binding redirects in the config, causing the endpoints not to load, should be fixed now
